version: 2.1

orbs:
  python: circleci/python@2.0.1 # Use the latest version

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - pytest
      - run:
          name: List files in the tests directory
          command: ls -R tests/
      - run:
          name: Run tests
          command: |
            source venv/bin/activate && pytest tests/ --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml

  build-package:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - setuptools
            - wheel
      - run:
          name: Build Python package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - store_artifacts:
          path: dist
          destination: ~/artifacts

workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python
