version: 2.1
orbs:
  python: circleci/python@2.0.3
  
jobs:
  build_and_test: 
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
     
      - run:
          name: Run tests
          command: python -m pytest --junitxml=results.xml
      - store_test_results:
          path: results.xml
      - store_artifacts: 
          path: results.xml
 
workflows:
  test_my_app:
    jobs:
      - build_and_test
