version: 2.1
orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
      - store_test_results:
          path: test-results
       - store_artifacts: # Store artifacts for later use
          path: test-results
  deploy: # Define the deploy job
    docker:
      - image: cimg/python:3.8 # Specify the Docker image for deployment
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to Heroku
          command: |
            cd /workspace
            heroku git:remote -a your-heroku-app-name # Replace with your Heroku app name
            git push heroku main # Push to Heroku

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
