version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    docker:
      - image: cimg/python:3.12.0
    parallelism: 4
    resource_class: large
    steps:
      - run:
          name: "Placeholder step for runner-test"
          command: echo "Runner test job is configured."

  build_and_test:
    docker:  # Specify that this job will use a Docker executor
      - image: circleci/python:3.8  # Use an appropriate Python image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest --junitxml=results.xml
      - store_test_results:
          path: results.xml
      - store_artifacts:
          path: results.xml

workflows:
  test_my_app:
    jobs:
      - build_and_test
