version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12.0
    resource_class: large
    parallelism: 4  # This allows up to 4 parallel instances of this job
    steps:
      - checkout
      - run:
          name: Install pytest and pytest-xdist
          command: pip install pytest pytest-xdist
      - run:
          name: Install pipenv
          command: pip install pipenv
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            # Run specific tests based on the CircleCI job index
            if [ "$CIRCLE_NODE_INDEX" -eq 0 ]; then
              python -m pytest tests/test_calculator.py --junitxml=results_1.xml
            elif [ "$CIRCLE_NODE_INDEX" -eq 1 ]; then
              python -m pytest tests/test_calculator.py --junitxml=results_2.xml
            elif [ "$CIRCLE_NODE_INDEX" -eq 2 ]; then
              python -m pytest tests/test_calculator.py --junitxml=results_3.xml
            elif [ "$CIRCLE_NODE_INDEX" -eq 3 ]; then
              python -m pytest tests/test_calculator.py --junitxml=results_4.xml
            fi
      - store_test_results:
          path: results_1.xml  # Adjusted for the first test set
      - store_artifacts:
          path: results_1.xml  # Adjusted for the first test set

workflows:
  test_my_app:
    jobs:
      - build_and_test:
          parallelism: 4  # Run up to 4 parallel instances of the job


