version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install pytest
    
      - run:
          name: Run tests
          command: |
            pytest test_calculator.py
      - store_test_results:
          path: calculatorTest.xml

  build-package:
    # Build Python package (for the calculator project)
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: python -m venv venv && source venv/bin/activate
      - run:
          name: Install build tools (setuptools and wheel)
          command: |
            pip install setuptools wheel
      - run:
          name: Build Python package
          command: |
            python setup.py sdist bdist_wheel
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - store_artifacts:
          path: dist
          destination: ~/artifacts

workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python
